# Generated by Django 4.2 on 2023-04-17 19:01

from django.db import migrations
import fgcomboapp.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('fgcomboapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fgcomboapp',
            name='videoFile',
            field=fgcomboapp.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
