# Generated by Django 4.2 on 2023-04-17 19:16

import django.core.validators
from django.db import migrations, models
import fgcomboapp.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('fgcomboapp', '0002_fgcomboapp_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comboNotation', models.TextField()),
                ('meterCost', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('moonSkillCost', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('moonDrive', models.BooleanField()),
                ('meterGain', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)])),
                ('notes', models.TextField(blank=True)),
                ('videoFile', fgcomboapp.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='FGComboApp',
        ),
    ]
