# Generated by Django 4.2 on 2023-04-17 20:22

import django.core.validators
from django.db import migrations, models
import fgcomboapp.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('fgcomboapp', '0003_combo_delete_fgcomboapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='comboNotation',
            field=models.TextField(verbose_name='Combo Notation'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='meterCost',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Meter Cost'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='meterGain',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='Meter Gain'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='moonDrive',
            field=models.BooleanField(verbose_name='Moon Drive'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='moonSkillCost',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Moon Skill Cost'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='videoFile',
            field=fgcomboapp.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/', verbose_name='Video File'),
        ),
    ]
