# Generated by Django 4.2 on 2023-04-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgcomboapp', '0005_combo_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='location',
            field=models.CharField(choices=[('ANY', 'Anywhere'), ('MID', 'Midscreen'), ('COR', 'Corner')], default='ANY', max_length=3),
        ),
    ]
