# Generated by Django 4.2 on 2023-05-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgcomboapp', '0007_game_alter_combo_damage_alter_combo_metercost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(default=None, null=True, verbose_name='Release Date'),
        ),
    ]
